/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;
	import ext.tree.ObjectTree;

	public class AuctionHallUI extends Dialog {
		public var tree:ObjectTree;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"Dialog","props":{"y":0,"x":0,"width":812,"stateNum":3,"height":482,"alpha":1,"align":"left"},"compId":2,"child":[{"type":"Tree","props":{"y":40,"x":300,"width":200,"var":"tree","scrollBarSkin":"comp/vscroll.png","runtime":"ext.tree.ObjectTree","height":400},"compId":36,"child":[{"type":"Box","props":{"y":0,"x":0,"width":200,"name":"render","height":38},"compId":37,"child":[{"type":"Button","props":{"y":0,"x":0,"width":200,"stateNum":3,"skin":"comp/btn_11.png","sizeGrid":"10,10,10,10","name":"imgBg1","labelStrokeColor":"#000000","alpha":1,"align":"left"},"compId":38},{"type":"Label","props":{"y":7,"x":0,"width":200,"valign":"middle","text":"空","strokeColor":"#ffe7c5,#fff3e3,#ddbf95","stroke":2,"name":"label","fontSize":22,"color":"#be8e8c","align":"center"},"compId":43}]}]}],"loadList":["comp/vscroll.png","comp/btn_11.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}